# Generated by Django 5.0.2 on 2024-05-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_productvariation_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
