# Generated by Django 5.0.2 on 2024-05-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_career'),
        ('core', '0007_alter_productvariation_color_and_more'),
    ]

    operations = [
    ]
