# Generated by Django 5.0.4 on 2024-05-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20240502_1828'),
        ('core', '0008_merge_20240502_2341'),
    ]

    operations = [
    ]
