# Generated by Django 5.0.3 on 2024-05-03 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20240502_1858'),
        ('core', '0009_merge_20240503_0234'),
    ]

    operations = [
    ]
